# Generated by Django 5.0.7 on 2024-07-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="play",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="users",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="plays",
        ),
        migrations.RemoveField(
            model_name="genre",
            name="plays",
        ),
        migrations.AddField(
            model_name="play",
            name="actors",
            field=models.ManyToManyField(to="theatre.actor"),
        ),
        migrations.AddField(
            model_name="play",
            name="genres",
            field=models.ManyToManyField(to="theatre.genre"),
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("performance", "row", "seat")},
        ),
    ]
