# Generated by Django 5.0.7 on 2024-07-29 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0002_alter_play_options_alter_reservation_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["row", "seat"]},
        ),
    ]
